/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhoRouteImport } from './routes/trabalho'
import { Route as SympliceRouteImport } from './routes/symplice'
import { Route as SolidRouteImport } from './routes/solid'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as NatraveRouteImport } from './routes/natrave'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicoSlugRouteImport } from './routes/servico.$slug'
import { Route as MarcaSlugRouteImport } from './routes/marca.$slug'

const TrabalhoRoute = TrabalhoRouteImport.update({
  id: '/trabalho',
  path: '/trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const SympliceRoute = SympliceRouteImport.update({
  id: '/symplice',
  path: '/symplice',
  getParentRoute: () => rootRouteImport,
} as any)
const SolidRoute = SolidRouteImport.update({
  id: '/solid',
  path: '/solid',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const NatraveRoute = NatraveRouteImport.update({
  id: '/natrave',
  path: '/natrave',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoSlugRoute = ServicoSlugRouteImport.update({
  id: '/servico/$slug',
  path: '/servico/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaSlugRoute = MarcaSlugRouteImport.update({
  id: '/marca/$slug',
  path: '/marca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/natrave': typeof NatraveRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/trabalho': typeof TrabalhoRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/natrave': typeof NatraveRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/trabalho': typeof TrabalhoRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/natrave': typeof NatraveRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/trabalho': typeof TrabalhoRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/natrave'
    | '/servicos'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/trabalho'
    | '/marca/$slug'
    | '/servico/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/natrave'
    | '/servicos'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/trabalho'
    | '/marca/$slug'
    | '/servico/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/natrave'
    | '/servicos'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/trabalho'
    | '/marca/$slug'
    | '/servico/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  NatraveRoute: typeof NatraveRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  SolidRoute: typeof SolidRoute
  SympliceRoute: typeof SympliceRoute
  TrabalhoRoute: typeof TrabalhoRoute
  MarcaSlugRoute: typeof MarcaSlugRoute
  ServicoSlugRoute: typeof ServicoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalho': {
      id: '/trabalho'
      path: '/trabalho'
      fullPath: '/trabalho'
      preLoaderRoute: typeof TrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symplice': {
      id: '/symplice'
      path: '/symplice'
      fullPath: '/symplice'
      preLoaderRoute: typeof SympliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solid': {
      id: '/solid'
      path: '/solid'
      fullPath: '/solid'
      preLoaderRoute: typeof SolidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natrave': {
      id: '/natrave'
      path: '/natrave'
      fullPath: '/natrave'
      preLoaderRoute: typeof NatraveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico/$slug': {
      id: '/servico/$slug'
      path: '/servico/$slug'
      fullPath: '/servico/$slug'
      preLoaderRoute: typeof ServicoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca/$slug': {
      id: '/marca/$slug'
      path: '/marca/$slug'
      fullPath: '/marca/$slug'
      preLoaderRoute: typeof MarcaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  NatraveRoute: NatraveRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  SolidRoute: SolidRoute,
  SympliceRoute: SympliceRoute,
  TrabalhoRoute: TrabalhoRoute,
  MarcaSlugRoute: MarcaSlugRoute,
  ServicoSlugRoute: ServicoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
